### ISSUE TITLE
Might be worth linking to this repo from hackage/package descriptions

### ISSUE THREAD

**Issue by phlummox** [NorfairKing/zifter#5]
None of the "Zifter" packages on hackage actually seem to say what zifter is, or why someone would want it - e.g. the documentation for the top-level module in the `zifter` package just starts by saying

> In most cases this should be the only module you import to start writing a zift.hs script

which is rather mysterious if I have no idea what a zift.hs script is.

Might be worth adding a link in the package `description` fields to this repository's README, so people can work out what they do. Also, the `homepage` field of a Cabal file is normally for the *package's* homepage, if any, not the developer's. And, if you add

```
source-repository head
  type:     git
  location: https://github.com/NorfairKing/zifter
```
to your Cabal file, hackage will automatically include a link to the repo from the package page on hackage, which can help people track down the repository if they need it.

**Comment by NorfairKing** [comment]
Zifter is deprecated, use `nix-shell` and `pre-commit` hooks instead.
I'll now archive this repo, didn't know anyone ever used this.
